package br.ufc.quixada.npi.gestaocompetencia.model.enums;

public enum Etapa {
	
	CADASTRO_COMPORTAMENTOS, CADASTRO_RESPONSABILIDADES, NORMALIZACAO_COMPORTAMENTOS,
	NORMALIZACAO_RESPONSABILIDADES, VALIDACAO_RESPONSABILIDADES, CONSOLIDACAO_RESPONSABILIDADES;
	
}
